linters-settings:
  lll:
    line-length: 79
    tab-width: 4

  varnamelen:
      ignore-decls:
        - i int
        - mi int
        - ok bool

linters:
  enable-all: true
  disable:
    - lll

    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: win_store_u?int\d*\.go  # Exclude on common int stores.
      linters:
        - dupl
    - path: win_store_.*_test\.go  # Exclude on common store tests.
      linters:
        - dupl
    - path: _test\.go  # Exclude on test files.
      linters:
        - cyclo
        - depguard
        - funlen
        - goconst
        - lll
        - maintidx
        - paralleltest
        - prealloc
        - revive
        - testpackage
        - wastedassign
        - unparam

run:
  timeout: 5m
  issues-exit-code: 2
  go: '1.22'
