linters-settings:
  lll:
    line-length: 79
    tab-width: 4

  varnamelen:
      ignore-decls:
        - i int
        - mi int
        - ok bool
      #  - re *regexp.Regexp
      #  - iT *iTst

linters:
  enable-all: true
  disable:
    - dupl
    - dupword
    - err113
    - exhaustruct
    - goconst
    - gofumpt
    - gosec
    - gosmopolitan
    - lll
    - nlreturn
    - stylecheck
    - varnamelen
    - wrapcheck
    - wsl

    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: ck_.+\.go  # Exclude on type check methods.
      linters:
        - dupl
    - path: cfg_validate_test\.go 
      linters:
        - dupl
    - path: chk_test\.go 
      linters:
        - dupl
    - path: _test\.go  # Exclude on test files.
      linters:
        - depguard
        - dupl
        - exhaustruct
        - funlen
        - goconst
        - cyclo
        #- goerr113
        - gofumpt
        - gosec
        - lll
        - maintidx
        - nlreturn
        - paralleltest
        - prealloc
        - revive
        - testpackage
        - varnamelen
        - wastedassign
        - wrapcheck
        - wsl
        - unparam

run:
  timeout: 5m
  issues-exit-code: 2
  go: '1.22'
